---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: mp-backend-service
  namespace: web-mp-dev
  labels:
    app: mp-backend
    component: backend
spec:
  selector:
    app: mp-backend
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
---
# Backend ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: mp-backend-config
  namespace: web-mp-dev
data:
  NODE_ENV: "development"
  PORT: "5000"
---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mp-backend
  namespace: web-mp-dev
  labels:
    app: mp-backend
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mp-backend
  template:
    metadata:
      labels:
        app: mp-backend
        component: backend
    spec:
      containers:
      - name: mp-backend
        image: default-route-openshift-image-registry.apps-crc.testing/openshift/mp-backend:1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: mp-backend-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: mp-backend-config
              key: PORT
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
# Backend Route (Opcional - para acceder directamente a la API)
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mp-backend-route
  namespace: web-mp-dev
  labels:
    app: mp-backend
    component: backend
spec:
  to:
    kind: Service
    name: mp-backend-service
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None